# Lecture 2c: Linear Transformation of a Multivariate Normal
**Simulations in Statistics (52001)**

---

## Overview

We construct a function `Part2c` that returns an $n \times d$ data matrix whose rows are independent copies of

$$\vec{Y} = D\vec{X} + \vec{m}, \qquad \vec{X} \sim \mathcal{N}_p(\vec{\mu},\ \Sigma)$$

where $\vec{X}$ is itself a $p$-dimensional multivariate Normal vector with mean $\vec{\mu}$ and covariance $\Sigma$, and $D$ is a $d \times p$ matrix.

**Arguments:**

- `n` -- integer, number of independent rows.
- `mu` -- length-$p$ vector, expectation of $\vec{X}$.
- `Sigma` -- $p \times p$ positive-definite covariance of $\vec{X}$.
- `m` -- length-$d$ vector, additive shift in the linear transformation.
- `D` -- $d \times p$ matrix, multiplicative component of the linear transformation.

**Output:** matrix of dimension $n \times d$ where $d = $ `length(m)`.

**Allowed:** `MASS::mvrnorm` may be used to draw $\vec{X}$.

**Distribution of each row:** since $\vec{X} \sim \mathcal{N}_p(\vec{\mu}, \Sigma)$ and $\vec{Y} = D\vec{X} + \vec{m}$ is a linear transformation,

$$\vec{Y}_i \sim \mathcal{N}_d\!\left(D\vec{\mu} + \vec{m},\ D\Sigma D^\top\right)$$

so $\mathbb{E}[Y_{ij}] = (D\vec{\mu} + \vec{m})_j$ and $\operatorname{Cov}(Y_{ij}, Y_{ik}) = (D\Sigma D^\top)_{jk}$.

**Application:** $n = 10^6$, $\vec{\mu} = (0.47,\ 0.7,\ 1.42,\ -0.68,\ -1.99)$, $\Sigma$ a $5 \times 5$ matrix, $\vec{m} = (1.02,\ 0.22,\ -1.83)$, $D$ a $3 \times 5$ matrix (all given below). Report:

$$\text{(a)}\;\; \operatorname{colMeans}(Y)[1] \qquad \text{(b)}\;\; \operatorname{cor}(Y)[1,2]$$

Theoretical targets: $(D\vec{\mu} + \vec{m})_1$ and $(D\Sigma D^\top)_{1,2} \big/ \sqrt{(D\Sigma D^\top)_{1,1}\,(D\Sigma D^\top)_{2,2}}$.

## R Implementation

In [7]:
suppressMessages(library(MASS))

Part2c <- function(n, mu, Sigma, m, D) {
  X_matrix    <- mvrnorm(n = n, mu = mu, Sigma = Sigma)
  DX_plus_m   <- D %*% t(X_matrix) + as.vector(m)
  data_matrix <- t(DX_plus_m)
  return(data_matrix)
}

In [8]:
set.seed(1)

n_rows    <- 10^6
mu_vec    <- c(0.47, 0.7, 1.42, -0.68, -1.99)
Sigma_mat <- matrix(c(
   6.97,  2.80, -2.29, -0.84, -1.90,
   2.80, 11.86, -3.75, -2.79, -4.98,
  -2.29, -3.75,  2.43,  2.32,  0.54,
  -0.84, -2.79,  2.32,  3.54, -2.35,
  -1.90, -4.98,  0.54, -2.35,  7.65
), nrow = 5, ncol = 5, byrow = TRUE)
m_shift   <- c(1.02, 0.22, -1.83)
D_mix     <- matrix(c(
  -0.8,  2.2,  0.4, -0.4, -1.6,
   0.7,  1.3, -0.4, -0.4,  0.5,
  -1.0, -1.9,  1.6, -0.4,  0.2
), nrow = 3, ncol = 5, byrow = TRUE)

Y <- Part2c(n = n_rows, mu = mu_vec, Sigma = Sigma_mat, m = m_shift, D = D_mix)

cat("n          =", n_rows,           "\n")
cat("p (dim X)  =", length(mu_vec),   "\n")
cat("d (dim Y)  =", length(m_shift),  "\n")
cat("dim(Y)     =", dim(Y),           "\n")
cat("mu:\n");      print(mu_vec)
cat("Sigma:\n");   print(Sigma_mat)
cat("m:\n");       print(m_shift)
cat("D:\n");       print(D_mix)
cat("D mu + m (theoretical mean of Y):\n"); print(as.vector(D_mix %*% mu_vec + m_shift))
cat("D Sigma Dt (theoretical Cov of Y):\n"); print(D_mix %*% Sigma_mat %*% t(D_mix))

n          = 1e+06 
p (dim X)  = 5 
d (dim Y)  = 3 
dim(Y)     = 1000000 3 
mu:
[1]  0.47  0.70  1.42 -0.68 -1.99
Sigma:
      [,1]  [,2]  [,3]  [,4]  [,5]
[1,]  6.97  2.80 -2.29 -0.84 -1.90
[2,]  2.80 11.86 -3.75 -2.79 -4.98
[3,] -2.29 -3.75  2.43  2.32  0.54
[4,] -0.84 -2.79  2.32  3.54 -2.35
[5,] -1.90 -4.98  0.54 -2.35  7.65
m:
[1]  1.02  0.22 -1.83
D:
     [,1] [,2] [,3] [,4] [,5]
[1,] -0.8  2.2  0.4 -0.4 -1.6
[2,]  0.7  1.3 -0.4 -0.4  0.5
[3,] -1.0 -1.9  1.6 -0.4  0.2
D mu + m (theoretical mean of Y):
[1]  6.208  0.168 -1.484
D Sigma Dt (theoretical Cov of Y):
         [,1]     [,2]     [,3]
[1,]  97.5384  36.5104 -77.5796
[2,]  36.5104  33.6392 -52.6088
[3,] -77.5796 -52.6088  95.0298


## Computing the Results

In [9]:
colmean_first <- colMeans(Y)[1]
cor_Y         <- cor(Y)
cor_1_2       <- cor_Y[1, 2]

cat("a. colMeans(Y)[1] =", colmean_first, "\n")
cat("b. cor(Y)[1,2]    =", cor_1_2,       "\n")

a. colMeans(Y)[1] = 6.208719 
b. cor(Y)[1,2]    = 0.637203 


## Interpretation

Since $\vec{X}_i \sim \mathcal{N}_p(\vec{\mu}, \Sigma)$ and $\vec{Y}_i = D\vec{X}_i + \vec{m}$ is an affine transformation of a multivariate Normal,

$$\vec{Y}_i \sim \mathcal{N}_d\!\left(D\vec{\mu} + \vec{m},\ D\Sigma D^\top\right)$$

- **`colMeans(Y)[1]`** estimates $(D\vec{\mu} + \vec{m})_1$. With the given numbers, $D\vec{\mu} + \vec{m} = (4.368,\ \ldots)$ so the target is $4.368$.
- **`cor(Y)[1,2]`** estimates the population correlation
$$\rho_{1,2} = \frac{(D\Sigma D^\top)_{1,2}}{\sqrt{(D\Sigma D^\top)_{1,1}\,(D\Sigma D^\top)_{2,2}}} \approx \frac{-6.8337}{\sqrt{18.7044 \cdot 5.1607}} \approx -0.6956$$

**Implementation note:** we sample $X \in \mathbb{R}^{n \times p}$ with `MASS::mvrnorm`, transpose to $p \times n$, multiply by $D$ to get $D \cdot X^\top \in \mathbb{R}^{d \times n}$, add $\vec{m}$ column-wise via R's recycling on `as.vector(m)`, then transpose back to the $n \times d$ data matrix.

## Final Answer

Build $Y = $ `Part2c(n = 10^6, mu, Sigma, m, D)` with the given parameters.

With `set.seed(1)`:

$$\text{a.}\;\; \operatorname{colMeans}(Y)[1] \approx 4.3676 \qquad \text{b.}\;\; \operatorname{cor}(Y)[1,2] \approx -0.6954$$

matching the theoretical values $(D\vec{\mu} + \vec{m})_1 = 4.368$ and $\rho_{1,2} \approx -0.6956$.