# Lecture 4a: Two-State MCMC Transition Matrix
**Simulations in Statistics (52001)**

---

## Overview

`Part4a(pi1, del, N)` constructs a two-state Markov transition matrix with stationary distribution $\vec{\pi}^{T} = (\pi_1, \pi_2)$, where $\pi_2 = 1 - \pi_1$.

For

$$\Pi = \begin{pmatrix}\pi_1 & \pi_2 \\ \pi_1 & \pi_2\end{pmatrix}, \qquad
D = \begin{pmatrix}\pi_2 & -\pi_2 \\ -\pi_1 & \pi_1\end{pmatrix},$$

the transition matrix is

$$P = \Pi + \delta D.$$

Since $\Pi^2 = \Pi$, $D^2 = D$, and $\Pi D = D \Pi = 0$, the matrix powers satisfy

$$P^N = \Pi + \delta^N D.$$

**Construction:**

1. Set $\pi_2 = 1 - \pi_1$.
2. Build $\Pi$, $D$, and $P = \Pi + \delta D$.
3. Compute `P.N` and `P.100` using the closed-form expression above.
4. Return all matrices so the requested entries can be read directly.


## R Implementation


In [13]:
Part4a <- function(pi1, del, N) {
  pi2 <- 1 - pi1
  pi_vec <- c(pi1, pi2)

  Pi <- matrix(rep(pi_vec, times = 2), nrow = 2, ncol = 2, byrow = TRUE)
  D <- matrix(c(pi2, -pi2, -pi1, pi1), nrow = 2, ncol = 2, byrow = TRUE)
  P <- Pi + del * D

  P.N <- Pi + del^N * D
  P.100 <- Pi + del^100 * D

  return(list(P = P, P.N = P.N, P.100 = P.100))
}


In [14]:
pi1_value <- 0.29
del_value <- 0.8
N_value <- 5

cat("pi1 =", pi1_value, "
")
cat("del =", del_value, "
")
cat("N   =", N_value, "
")


pi1 = 0.29 


del = 0.8 
N   = 5 


## Computing the Results


In [15]:
mcmc_results <- Part4a(
  pi1 = pi1_value,
  del = del_value,
  N = N_value
)

P <- mcmc_results$P
P.N <- mcmc_results$P.N
P.100 <- mcmc_results$P.100

cat("P:
"); print(P)
cat("P.N:
"); print(P.N)
cat("P.100:
"); print(P.100)
cat("
")
cat("a. P.N[1,1]   =", P.N[1, 1], "
")
cat("b. P.N[2,1]   =", P.N[2, 1], "
")
cat("c. P.100[1,1] =", P.100[1, 1], "
")
cat("d. P.100[2,1] =", P.100[2, 1], "
")


P:
      [,1]  [,2]
[1,] 0.858 0.142
[2,] 0.058 0.942
P.N:
          [,1]      [,2]
[1,] 0.5226528 0.4773472
[2,] 0.1949728 0.8050272
P.100:
     [,1] [,2]
[1,] 0.29 0.71
[2,] 0.29 0.71

a. P.N[1,1]   = 0.5226528 
b. P.N[2,1]   = 0.1949728 
c. P.100[1,1] = 0.29 
d. P.100[2,1] = 0.29 
